package politicConnect.user;

public enum RegionCity {

    // --- 특별시 / 광역시 / 특별자치시 ---
    SEOUL,
    BUSAN,
    DAEGU,
    INCHEON,
    GWANGJU,
    DAEJEON,
    ULSAN,
    SEJONG,

    // --- 경기도 ---
    GYEONGGI_SUWON,
    GYEONGGI_SEONGNAM,
    GYEONGGI_GOYANG,
    GYEONGGI_YONGIN,
    GYEONGGI_BUCHEON,
    GYEONGGI_ANSAN,
    GYEONGGI_ANYANG,
    GYEONGGI_NAMYANGJU,
    GYEONGGI_HWASEONG,
    GYEONGGI_PYEONGTAEK,
    GYEONGGI_UIJEONGBU,
    GYEONGGI_SIHEUNG,
    GYEONGGI_PAJU,
    GYEONGGI_GIMPO,
    GYEONGGI_GWANGMYEONG,
    GYEONGGI_GUNPO,
    GYEONGGI_GWANGJU,
    GYEONGGI_ICHEON,
    GYEONGGI_OSAN,
    GYEONGGI_ANSEONG,
    GYEONGGI_UIWANG,
    GYEONGGI_HANAM,
    GYEONGGI_POCHEON,
    GYEONGGI_YEOJU,
    GYEONGGI_YANGJU,
    GYEONGGI_DONGDUCHEON,
    GYEONGGI_GURI,

    // --- 강원특별자치도 ---
    GANGWON_CHUNCHEON,
    GANGWON_WONJU,
    GANGWON_GANGNEUNG,
    GANGWON_DONGHAE,
    GANGWON_SOKCHO,
    GANGWON_SAMCHEOK,

    // --- 충청북도 ---
    CHUNGBUK_CHEONGJU,
    CHUNGBUK_CHUNGJU,
    CHUNGBUK_JECHEON,

    // --- 충청남도 ---
    CHUNGNAM_CHEONAN,
    CHUNGNAM_GONGJU,
    CHUNGNAM_BORYEONG,
    CHUNGNAM_ASAN,
    CHUNGNAM_SEOSAN,
    CHUNGNAM_NONSAN,
    CHUNGNAM_GYERYONG,
    CHUNGNAM_DANGJIN,

    // --- 전북특별자치도 ---
    JEONBUK_JEONJU,
    JEONBUK_GUNSAN,
    JEONBUK_IKSAN,
    JEONBUK_JEONGEUP,
    JEONBUK_NAMWON,
    JEONBUK_GIMJE,

    // --- 전라남도 ---
    JEONNAM_MOKPO,
    JEONNAM_YEOSU,
    JEONNAM_SUNCHEON,
    JEONNAM_NAJU,
    JEONNAM_GWANGYANG,

    // --- 경상북도 ---
    GYEONGBUK_POHANG,
    GYEONGBUK_GYEONGJU,
    GYEONGBUK_GIMCHEON,
    GYEONGBUK_ANDONG,
    GYEONGBUK_GUMI,
    GYEONGBUK_YEONGJU,
    GYEONGBUK_YEONGCHEON,
    GYEONGBUK_SANGJU,
    GYEONGBUK_MUNGYEONG,
    GYEONGBUK_GYEONGSAN,

    // --- 경상남도 ---
    GYEONGNAM_CHANGWON,
    GYEONGNAM_JINJU,
    GYEONGNAM_TONGYEONG,
    GYEONGNAM_SACHEON,
    GYEONGNAM_GIMHAE,
    GYEONGNAM_MILYANG,
    GYEONGNAM_GEOJE,
    GYEONGNAM_YANGSAN,

    // --- 제주특별자치도 ---
    JEJU_JEJU,
    JEJU_SEOGWIPO
}
